### ISSUE TITLE
Organise venue and Dates

### ISSUE THREAD

**Issue by JonTheNiceGuy** [oggcamp/OggCamp-Activities#15]

**Comment by lauracowen** [comment]
A thought I had on way home after a conversation about London as a potential venue. I know venues are difficult to find so this is just a thought to consider in discussions. If there's a London option and a viable alternative to London, i think it should be the non-London option. London has *a lot* of meetup events (inclusion foss talk live), even if it doesn't have exactly the same thing as an oggcamp. One of the cool things about oggcamp is that it tours round lots of places that have fewer such events. Yes, there might be more people in London to come but we seem to have a number of local ppl at each city we've been in. And at each place we've had some regulars not come while some come regardless of distance. I think there's a strength in oggcamp not being in London and being more inclusive of the rest of the country (sorry, Joe). The model you used this year of having someone on the ground in Canterbury but the organiser elsewhere seemed to work (in the past, it was always about having the main organiser local, which made it more difficult). If we can get someone in Edinburgh/Glasgow, say, it could be outside England even! Or Cardiff would be good.... (okay, I'll be quiet now)

**Comment by aptanet** [comment]
Personally, in spite of being at the end of a single train journey to London I'm not entirely keen on the idea. Even ignoring the fact that I camp (which would be awkward, although Chertsey has a site) I would imagine it pushes the accommodation costs up.

I was going to suggest that if we had somebody near Bristol with a venue that might be good, but Cardiff sounds good. I would suggest Portsmouth, but a) putting it too far south isn't a good idea and b) I'd probably be asked if there are any good venues and that involves work! ;-)

**Comment by JonTheNiceGuy** [comment]
Venue was selected. Closed.
