### ISSUE TITLE
Buy T-Shirts and Mugs

### ISSUE THREAD

**Issue by JonTheNiceGuy** [oggcamp/OggCamp-Activities#3]
Requires scoping activity based on ticket sales
T-Shirt design provided as part of #1

**Comment by marxjohnson** [comment]
Note, we need sponsor logos before we can order t-shirts.

**Comment by JonTheNiceGuy** [comment]
Need to determine lead time on merch ordering - add timeline to T&C doc
Contact Jen for requote on T-Shirt/Mug/Sticker work...
